name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: npm clean install
        run: npm ci

      - name: Check formatting
        run: npx prettier --check .

  lint:
    name: ESLint (webview-ui)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: webview-ui/package-lock.json

      - name: npm clean install
        run: npm ci
        working-directory: webview-ui

      - name: Lint
        run: npm run lint
        working-directory: webview-ui

  build:
    name: Type check & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: npm clean install
        run: |
          (cd webview-ui ; npm ci)
          npm ci

      - name: Type check
        run: npm run check-types

      - name: Build vscode extension
        run: npm run package

      - name: Upload extension artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextflow-vsix
          path: build/nextflow.vsix
